stages:
  - build
  - test
  - package
  - deploy

# Use official Maven + OpenJDK image for building and deploying
image: maven:3.8.4-openjdk-17

# Docker-in-Docker service to manage Docker containers
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2  # Optimizing Docker's file system driver
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Java and Maven"
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
  - export PATH=$JAVA_HOME/bin:$PATH

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - echo "Running unit + integration tests with coverage..."
    - mvn verify
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
      - target/site/jacoco-both/index.html
      - target/site/jacoco-both/

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  script:
    - echo "Building Docker images using Docker Compose"
    - docker-compose up --build -d  # Build and deploy using Docker Compose
  only:
    - master  # Deploy only on the master branch
