services:
  app:
    build: .
    container_name: helloapp-staging-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
